remote_theme: pmarsceill/just-the-docs
logo: "https://raw.githubusercontent.com/v1a0/imgs/c1fb6314d43dec006be4cd747425c0bb8b24e07c/sqllex/sqllex-logo.svg"
color_scheme: light

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/v1a0/sqllex"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

search_enabled: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false


