remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

title: "Sqllex"

description: "Better than sqlite3. Seriously, try it out!"

url: "v1a0.dev/sqllex"

baseurl: "/sqllex"

lang: en